import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {toPng,toSvg} from 'html-to-image';
import {addDays,applyTaskDrag,daysBetween,emptyTask,sampleProject,uid,validateImport} from './data';
import type {TaskDragMode} from './data';
import {loadProjects,saveProjects} from './db';
import type {ExportFile,Project,Task,ViewMode} from './types';

const clone=<T,>(x:T):T=>structuredClone(x);
function download(data:string,name:string,type:string){const a=document.createElement('a');a.href=data.startsWith('data:')?data:URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();if(!data.startsWith('data:'))URL.revokeObjectURL(a.href)}
function esc(v:string){return `"${v.replaceAll('"','""')}"`}

export default function App(){
 const [projects,setProjects]=useState<Project[]>([]),[activeId,setActiveId]=useState(''),[view,setView]=useState<ViewMode>(()=>(localStorage.getItem('gantt-view') as ViewMode)||'week');
 const [ready,setReady]=useState(false),[editing,setEditing]=useState<Task|null>(null),[notice,setNotice]=useState(''),[history,setHistory]=useState<Project[][]>([]),[future,setFuture]=useState<Project[][]>([]);
 const fileRef=useRef<HTMLInputElement>(null),chartRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{loadProjects().then(p=>{const data=p.length?p:[sampleProject()];setProjects(data);setActiveId(data[0].id);setReady(true)}).catch(()=>setNotice('無法開啟瀏覽器本機資料庫。'))},[]);
 useEffect(()=>{if(ready){const timer=setTimeout(()=>saveProjects(projects).catch(()=>setNotice('自動儲存失敗，請先匯出備份。')),250);return()=>clearTimeout(timer)}},[projects,ready]);
 useEffect(()=>localStorage.setItem('gantt-view',view),[view]);
 const project=projects.find(p=>p.id===activeId)||projects[0];
 const commit=(next:Project[])=>{setHistory(h=>[...h.slice(-39),clone(projects)]);setFuture([]);setProjects(next)};
 const patchProject=(fn:(p:Project)=>Project)=>commit(projects.map(p=>p.id===project.id?{...fn(p),updatedAt:new Date().toISOString()}:p));
 const undo=()=>{const prev=history.at(-1);if(!prev)return;setFuture(f=>[clone(projects),...f]);setProjects(prev);setHistory(h=>h.slice(0,-1))};
 const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,clone(projects)]);setProjects(next);setFuture(f=>f.slice(1))};
 const addProject=()=>{const now=new Date().toISOString();const p={id:uid(),name:'未命名專案',description:'',createdAt:now,updatedAt:now,tasks:[emptyTask()]};commit([...projects,p]);setActiveId(p.id)};
 const deleteProject=()=>{if(projects.length===1)return setNotice('至少需要保留一個專案。');if(confirm(`刪除「${project.name}」前，建議先匯出 JSON 備份。確定刪除？`)){const n=projects.filter(p=>p.id!==project.id);commit(n);setActiveId(n[0].id)}};
 const updateTask=(task:Task)=>patchProject(p=>({...p,tasks:p.tasks.map(t=>t.id===task.id?task:t)}));
 const moveTask=(i:number,d:number)=>{const j=i+d;if(j<0||j>=project.tasks.length)return;patchProject(p=>{const tasks=[...p.tasks];[tasks[i],tasks[j]]=[tasks[j],tasks[i]];return{...p,tasks}})};
 const exportJson=()=>{const data:ExportFile={schema:'gantt-local',version:1,exportedAt:new Date().toISOString(),projects};download(JSON.stringify(data,null,2),'gantt-backup.json','application/json')};
 const importJson=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{const data:unknown=JSON.parse(await f.text());if(!validateImport(data))throw Error();if(confirm(`已驗證檔案，共 ${data.projects.length} 個專案。\n按「確定」合併；按「取消」則不變更資料。`)){const ids=new Set(projects.map(p=>p.id));const incoming=data.projects.map(p=>ids.has(p.id)?{...p,id:uid(),name:`${p.name}（匯入）`}:p);commit([...projects,...incoming]);setNotice('匯入完成，原有專案已保留。')}}catch{setNotice('匯入失敗：檔案格式或版本不正確，資料未變更。')}};
 const exportCsv=()=>{const rows=[['名稱','開始日期','結束日期','進度','負責人','顏色','里程碑','相依工作','備註'],...project.tasks.map(t=>[t.name,t.start,t.end,String(t.progress),t.owner,t.color,t.milestone?'是':'否',t.dependencies.map(id=>project.tasks.find(x=>x.id===id)?.name||id).join(';'),t.notes])];download('\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\n'),`${project.name}.csv`,'text/csv;charset=utf-8')};
 const exportImage=async(type:'png'|'svg')=>{if(!chartRef.current)return;try{const fn=type==='png'?toPng:toSvg;download(await fn(chartRef.current,{backgroundColor:'#fff',pixelRatio:2}),`${project.name}.${type}`,`image/${type}`)}catch{setNotice('圖片產生失敗，請稍後再試。')}};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();if(e.shiftKey)redo();else undo()}if((e.ctrlKey||e.metaKey)&&e.key==='y'){e.preventDefault();redo()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)});
 if(!ready||!project)return <main className="loading">正在開啟本機專案…</main>;
 return <div className="app">
  <header><div className="brand"><span className="brandmark">序</span><div><b>時序 Gantt</b><small>本機專案工作台</small></div></div><div className="header-actions"><button onClick={undo} disabled={!history.length} title="Ctrl/⌘ + Z">復原</button><button onClick={redo} disabled={!future.length}>重做</button><button onClick={()=>{exportJson();setNotice('手動快照已下載。')}}>建立快照</button><div className="menu"><button className="primary">匯出 ▾</button><div className="menu-pop"><button onClick={exportJson}>JSON 備份</button><button onClick={exportCsv}>CSV 表格</button><button onClick={()=>exportImage('png')}>PNG 圖片</button><button onClick={()=>exportImage('svg')}>SVG 向量圖</button><button onClick={()=>print()}>列印／PDF</button></div></div><button onClick={()=>fileRef.current?.click()}>匯入</button><input ref={fileRef} hidden type="file" accept="application/json" onChange={importJson}/></div></header>
  <div className="local-note" role="note"><b>資料只儲存在這台裝置</b><span>不是雲端備份；請定期建立 JSON 快照，以免清除瀏覽器資料後遺失。</span></div>
  {notice&&<div className="toast" role="status">{notice}<button aria-label="關閉通知" onClick={()=>setNotice('')}>×</button></div>}
  <main>
   <section className="projectbar"><label>目前專案<select value={project.id} onChange={e=>setActiveId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button onClick={addProject}>＋ 新專案</button><button onClick={deleteProject} className="danger">刪除專案</button><div className="project-meta"><input aria-label="專案名稱" value={project.name} onChange={e=>patchProject(p=>({...p,name:e.target.value}))}/><input aria-label="專案說明" value={project.description} placeholder="新增專案說明…" onChange={e=>patchProject(p=>({...p,description:e.target.value}))}/></div></section>
   <section className="workspace"><div className="workspace-title"><div><h1>{project.name}</h1><p>{project.tasks.length} 項工作 · 上次修改 {new Date(project.updatedAt).toLocaleString('zh-TW',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})} · 滾輪縮放、拖曳空白處平移</p></div><div className="view-switch" aria-label="時間檢視">{(['day','week','month'] as const).map(v=><button className={view===v?'active':''} key={v} onClick={()=>setView(v)}>{v==='day'?'日':v==='week'?'週':'月'}</button>)}</div><button className="primary add" onClick={()=>patchProject(p=>({...p,tasks:[...p.tasks,emptyTask()]}))}>＋ 新增工作</button></div>
    <Gantt project={project} view={view} chartRef={chartRef} onEdit={t=>setEditing(clone(t))} onUpdate={updateTask} onDelete={id=>{if(confirm('確定刪除這項工作？'))patchProject(p=>({...p,tasks:p.tasks.filter(t=>t.id!==id).map(t=>({...t,dependencies:t.dependencies.filter(x=>x!==id)}))}))}} onCopy={t=>patchProject(p=>({...p,tasks:[...p.tasks,{...clone(t),id:uid(),name:`${t.name}（副本）`}]}))} onMove={moveTask}/>
   </section>
  </main>
  {editing&&<TaskDialog task={editing} tasks={project.tasks} onClose={()=>setEditing(null)} onSave={t=>{updateTask(t);setEditing(null)}}/>}
  <footer>時序 Gantt · 所有資料皆留在您的瀏覽器 · <button onClick={exportJson}>立即備份</button></footer>
 </div>
}

type TaskDrag={task:Task;mode:TaskDragMode;startX:number;delta:number};
function Gantt({project,view,chartRef,onEdit,onUpdate,onDelete,onCopy,onMove}:{project:Project;view:ViewMode;chartRef:React.RefObject<HTMLDivElement|null>;onEdit:(t:Task)=>void;onUpdate:(t:Task)=>void;onDelete:(id:string)=>void;onCopy:(t:Task)=>void;onMove:(i:number,d:number)=>void}){
 const baseScale=view==='day'?42:view==='week'?18:6;
 const [zoom,setZoom]=useState(1),[panning,setPanning]=useState(false),[dragging,setDragging]=useState<TaskDrag|null>(null);
 const timelineRef=useRef<HTMLDivElement>(null),pan=useRef<{x:number;scroll:number}|null>(null),drag=useRef<TaskDrag|null>(null),zoomAnchor=useRef<{zoom:number;scroll:number;offset:number}|null>(null);
 const scale=baseScale*zoom;
 useLayoutEffect(()=>{const anchor=zoomAnchor.current;if(!anchor||!timelineRef.current)return;timelineRef.current.scrollLeft=(anchor.scroll+anchor.offset)*(zoom/anchor.zoom)-anchor.offset;zoomAnchor.current=null},[zoom]);
 const renderedTasks=project.tasks.map(t=>dragging?.task.id===t.id?applyTaskDrag(t,dragging.mode,dragging.delta):t);
 const all=renderedTasks.flatMap(t=>[t.start,t.end]);const min=all.length?all.sort()[0]:new Date().toISOString().slice(0,10);const origin=addDays(min,-3);const max=all.length?[...all].sort().at(-1)!:addDays(min,30);const total=Math.max(40,daysBetween(origin,max)+8);const ticks=Array.from({length:total},(_,i)=>addDays(origin,i));
 const zoomTimeline=(e:React.WheelEvent<HTMLDivElement>)=>{if(!e.deltaY)return;e.preventDefault();const rect=e.currentTarget.getBoundingClientRect(),offset=Math.max(0,Math.min(e.currentTarget.clientWidth,e.clientX-rect.left)),next=Math.max(.45,Math.min(3.5,zoom*Math.exp(-e.deltaY*.0015)));if(next===zoom)return;zoomAnchor.current={zoom,scroll:e.currentTarget.scrollLeft,offset};setZoom(next)};
 const startPan=(e:React.PointerEvent<HTMLDivElement>)=>{if(e.button!==0)return;const target=e.target;if(target instanceof Element&&target.closest('.bar,.resize-handle'))return;pan.current={x:e.clientX,scroll:e.currentTarget.scrollLeft};e.currentTarget.setPointerCapture(e.pointerId);setPanning(true);e.preventDefault()};
 const movePan=(e:React.PointerEvent<HTMLDivElement>)=>{if(pan.current)e.currentTarget.scrollLeft=pan.current.scroll-(e.clientX-pan.current.x)};
 const endPan=(e:React.PointerEvent<HTMLDivElement>)=>{if(pan.current&&e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);pan.current=null;setPanning(false)};
 const startTaskDrag=(e:React.PointerEvent<HTMLElement>,task:Task,mode:TaskDragMode)=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();const bar=(e.currentTarget as HTMLElement).closest('.bar') as HTMLElement|null;if(!bar)return;const next={task,mode,startX:e.clientX,delta:0};drag.current=next;setDragging(next);bar.setPointerCapture(e.pointerId)};
 const moveTaskDrag=(e:React.PointerEvent<HTMLButtonElement>)=>{const current=drag.current;if(!current)return;const delta=Math.round((e.clientX-current.startX)/scale);if(delta===current.delta)return;const next={...current,delta};drag.current=next;setDragging(next)};
 const endTaskDrag=(e:React.PointerEvent<HTMLButtonElement>)=>{const current=drag.current;if(!current)return;const next=applyTaskDrag(current.task,current.mode,current.delta);if(next.start!==current.task.start||next.end!==current.task.end)onUpdate(next);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);drag.current=null;setDragging(null)};
 const cancelTaskDrag=()=>{drag.current=null;setDragging(null)};
 return <div className="gantt" ref={chartRef}><div className="task-pane"><div className="table-head"><span>工作名稱</span><span>日期／負責人</span><span>進度</span><span>操作</span></div>{renderedTasks.map((t,i)=><div className="task-row" key={t.id}><button className="task-name" onClick={()=>onEdit(t)}>{t.milestone&&<i>◆</i>}<span>{t.name}</span><small>{t.start} → {t.end} · {t.owner||'未指派'}</small></button><div className="progress"><span style={{width:`${t.progress}%`}}/><b>{t.progress}%</b></div><div className="row-actions"><button onClick={()=>onMove(i,-1)} aria-label="向上移動">↑</button><button onClick={()=>onMove(i,1)} aria-label="向下移動">↓</button><button onClick={()=>onCopy(t)} aria-label="複製">⧉</button><button onClick={()=>onDelete(t.id)} aria-label="刪除">×</button></div></div>)}</div>
 <div ref={timelineRef} className={`timeline${panning?' panning':''}`} role="region" aria-label="時間軸，可使用滾輪縮放或拖曳平移" style={{'--scale':`${scale}px`} as React.CSSProperties} onWheel={zoomTimeline} onPointerDown={startPan} onPointerMove={movePan} onPointerUp={endPan} onPointerCancel={endPan}><div className="dates" style={{width:total*scale}}>{ticks.map((d,i)=><span key={d} className={new Date(d+'T00:00:00').getDay()===1?'major':''} style={{left:i*scale,width:scale}}>{view==='month'?(new Date(d+'T00:00:00').getDate()===1?new Date(d+'T00:00:00').toLocaleDateString('zh-TW',{month:'short'}):''):view==='week'?(i%7===0?new Date(d+'T00:00:00').toLocaleDateString('zh-TW',{month:'numeric',day:'numeric'}):''):new Date(d+'T00:00:00').getDate()}</span>)}</div><div className="grid" style={{width:total*scale}}>{renderedTasks.map(t=>{const left=daysBetween(origin,t.start)*scale;const width=Math.max(scale*.65,(daysBetween(t.start,t.end)+1)*scale);const active=dragging?.task.id===t.id;return <div className="lane" key={t.id}>{t.milestone?<button aria-label={`${t.name} 里程碑`} title={t.name} className="diamond" style={{left,background:t.color}} onClick={()=>onEdit(t)}/>:<button className={`bar${active?' dragging':''}`} title="拖曳以平移；拖曳左右邊緣調整日期" style={{left,width,background:t.color}} onPointerDown={e=>startTaskDrag(e,t,'move')} onPointerMove={moveTaskDrag} onPointerUp={endTaskDrag} onPointerCancel={cancelTaskDrag}><span className="drag-preview">{t.start} → {t.end}</span><span className="resize-handle start" aria-label="調整開始日期" title="調整開始日期" onPointerDown={e=>startTaskDrag(e,t,'start')}/><span className="bar-progress" style={{width:`${t.progress}%`}}/><span className="resize-handle end" aria-label="調整結束日期" title="調整結束日期" onPointerDown={e=>startTaskDrag(e,t,'end')}/><b>{t.name}</b></button>}</div>})}</div></div></div>
}

function TaskDialog({task,tasks,onClose,onSave}:{task:Task;tasks:Task[];onClose:()=>void;onSave:(t:Task)=>void}){const [t,setT]=useState(task);const valid=t.name.trim()&&t.start<=t.end;return <div className="modal" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form role="dialog" aria-modal="true" aria-labelledby="dialog-title" onSubmit={e=>{e.preventDefault();if(valid)onSave(t)}}><div className="dialog-head"><div><small>工作詳細資料</small><h2 id="dialog-title">編輯工作</h2></div><button type="button" onClick={onClose} aria-label="關閉">×</button></div><label>工作名稱<input autoFocus required value={t.name} onChange={e=>setT({...t,name:e.target.value})}/></label><div className="form-grid"><label>開始日期<input type="date" required value={t.start} onChange={e=>setT({...t,start:e.target.value})}/></label><label>結束日期<input type="date" required min={t.start} value={t.end} onChange={e=>setT({...t,end:e.target.value})}/></label><label>完成進度 <b>{t.progress}%</b><input type="range" min="0" max="100" value={t.progress} onChange={e=>setT({...t,progress:+e.target.value})}/></label><label>負責人<input value={t.owner} onChange={e=>setT({...t,owner:e.target.value})}/></label><label>顏色<input className="color" type="color" value={t.color} onChange={e=>setT({...t,color:e.target.value})}/></label><label className="check"><input type="checkbox" checked={t.milestone} onChange={e=>setT({...t,milestone:e.target.checked,end:e.target.checked?t.start:t.end})}/>設為里程碑</label></div><fieldset><legend>工作相依關係</legend><div className="deps">{tasks.filter(x=>x.id!==t.id).map(x=><label key={x.id}><input type="checkbox" checked={t.dependencies.includes(x.id)} onChange={e=>setT({...t,dependencies:e.target.checked?[...t.dependencies,x.id]:t.dependencies.filter(id=>id!==x.id)})}/>{x.name}</label>)}</div></fieldset><label>備註<textarea rows={3} value={t.notes} onChange={e=>setT({...t,notes:e.target.value})}/></label>{!valid&&<p className="error">請填寫名稱，且結束日期不可早於開始日期。</p>}<div className="dialog-actions"><button type="button" onClick={onClose}>取消</button><button className="primary" disabled={!valid}>儲存變更</button></div></form></div>}
