// Schema version of WorkspaceData/ExportFile. The one place a future field addition
// that isn't safely defaultable bumps — db.ts's migrateWorkspace and data.ts's
// validation import it instead of each holding their own copy of the number.
export const CURRENT_WORKSPACE_VERSION = 5;

export type ViewMode = 'day' | 'week' | 'month';
export type TaskStatus = 'backlog' | 'scheduled' | 'in_progress' | 'completed';
export type TaskPriority = 'low' | 'medium' | 'high';
export type RecurrenceFrequency = 'daily' | 'weekly' | 'monthly';
export type Weekday = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export interface RecurrenceRule {
  frequency: RecurrenceFrequency;
  startDate: string;
  endDate: string;
  hoursPerOccurrence: number;
  /** JavaScript UTC weekday: 0 is Sunday, 6 is Saturday. */
  weekdays: Weekday[];
  /** Calendar days 1 through 31. Invalid calendar dates are skipped. */
  monthDays: number[];
}

export interface Task {
  id: string;
  name: string;
  /** @deprecated Kept only so old exports can be migrated without data loss. */
  start: string | null;
  /** @deprecated Kept only so old exports can be migrated without data loss. */
  end: string | null;
  deadline: string | null;
  estimatedHours: number;
  priority: TaskPriority;
  status: TaskStatus;
  notes: string;
  owner: string;
  color: string;
  createdAt: string;
  updatedAt: string;
  /** Null means this is a root work item. */
  parentId?: string | null;
  /** Stable sibling ordering; old data falls back to array order. */
  order?: number;
  /** A single explicit recurring schedule rule for leaf tasks. */
  recurrence?: RecurrenceRule | null;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  tasks: Task[];
}

export interface Allocation {
  id: string;
  taskId: string;
  date: string;
  allocatedHours: number;
  /** Present only while this allocation is generated by the task recurrence rule. */
  recurrenceId?: string;
}

export interface WorkspaceData {
  version: typeof CURRENT_WORKSPACE_VERSION;
  projects: Project[];
  allocations: Allocation[];
}

export interface ExportFile extends WorkspaceData {
  schema: 'gantt-capacity-local';
  exportedAt: string;
}
